# Generated by Django 4.2.5 on 2023-09-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255, unique=True)),
                ('alias', models.CharField(max_length=255)),
                ('is_valid', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
